ci: Enhance deployment with multi-branch triggers (#57)
### Summary

**Type:** ci

* **What kind of change does this PR introduce?** 
  * Updates the deployment and merge workflows in GitHub Actions.

* **What is the current behavior?** 
* Lacks storing SHA in the distribution and explicit permissions in
workflows.
  * Simplified workflow steps for merging and tagging.

* **What is the new behavior?**
  * Adds a step to store the release SHA in JSON file during deployment.
  * Renames "Merge and Tag" workflow to "Merge".
* Grants explicit permissions for contents, actions, and pull-requests.
* Introduces `trigger-push` step to trigger the staging deployment
post-merge.
* Updates deployment workflow to include releases for `test` and adds
`workflow_dispatch` and `workflow_call`.
  * Merges to `main` branch after deploying from `test` branch.

* **Does this PR introduce a breaking change?** 
  * No.

* **Has Testing been included for this PR?**
* No explicit tests are mentioned, but GitHub Actions workflows will be
tested implicitly through usage.

### Other Information

Added entries `/test-results` and `/playwright-report` to `.gitignore`
to exclude test artifacts from version control.

diff --git a/.github/workflows/job.merge.yml b/.github/workflows/job.merge.yml
--- a/.github/workflows/job.merge.yml
+++ b/.github/workflows/job.merge.yml
@@ -1,4 +1,4 @@
-name: Merge and Tag
+name: Merge
 
 on:
   workflow_call:
@@ -10,6 +10,10 @@ on:
         required: true
         type: string
 
+permissions:
+  contents: write
+  actions: write
+  pull-requests: write
 jobs:
   merge:
     runs-on: ubuntu-latest
@@ -33,6 +37,28 @@ jobs:
         git merge --ff-only origin/${{ inputs.target-branch }}
 
     - name: Push changes to ${{ inputs.base-branch }}
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       if: success()
       run: |
         git push origin ${{ inputs.base-branch }}
+
+  trigger-push:
+    needs:
+      - merge
+    runs-on: ubuntu-latest
+    steps:
+      - name: Trigger staging deployment
+        run: |
+          set -e
+          
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/${{ github.repository }}/actions/workflows/pipeline.deployment.yml/dispatches \
+            -d '{"ref":"${{ inputs.base-branch }}"}')
+          
+          if [[ $response != "204" ]]; then
+            echo "Error: Unexpected response status code $response"
+            exit 1
+          fi
